export const sviProizvodi = [
    {
        id: 1,
        ime: 'Zlatni lančić',
        opis: 'Ovaj zlatni lančić je savršen dodatak svakom outfitu. Dizajniran je za žene koje cijene stil, sofisticiranost i individualnost. Vjerujemo da nakit ima moć da promijeni način na koji se osjećate, dodajući dašak luksuza i elegancije vašem izgledu',
        kategorija: "Ogrlice",
        cijena: 21.95,
        slikaSrc: '/ogrlica1.jpeg',
        slikaAlt: 'Neki opis proizvoda',
    },
    {
        id: 2,
        name: 'Zlatni lančić',
        description: 'Ovaj zlatni lančić je savršen dodatak svakom outfitu. Dizajniran je za žene koje cijene stil, sofisticiranost i individualnost. Vjerujemo da nakit ima moć da promijeni način na koji se osjećate, dodajući dašak luksuza i elegancije vašem izgledu',
        kategorija: "Ogrlice",
        price: 21.95,
        imageSrc: '/ogrlica1.jpeg',
        imageAlt: 'Neki opis proizvoda',
    },
    {
        id: 3,
        name: 'Zlatni lančić',
        description: 'Ovaj zlatni lančić je savršen dodatak svakom outfitu. Dizajniran je za žene koje cijene stil, sofisticiranost i individualnost. Vjerujemo da nakit ima moć da promijeni način na koji se osjećate, dodajući dašak luksuza i elegancije vašem izgledu',
        kategorija: "Ogrlice",
        price: 21.95,
        imageSrc: '/ogrlica1.jpeg',
        imageAlt: 'Neki opis proizvoda',
    },
    {
        id: 4,
        name: 'Zlatni lančić',
        description: 'Ovaj zlatni lančić je savršen dodatak svakom outfitu. Dizajniran je za žene koje cijene stil, sofisticiranost i individualnost. Vjerujemo da nakit ima moć da promijeni način na koji se osjećate, dodajući dašak luksuza i elegancije vašem izgledu',
        kategorija: "Ogrlice",
        price: 21.95,
        imageSrc: '/ogrlica1.jpeg',
        imageAlt: 'Neki opis proizvoda',
    },

    {
        id: 5,
        name: 'Zlatne nausnice',
        description: 'Ovaj zlatni lančić je savršen dodatak svakom outfitu. Dizajniran je za žene koje cijene stil, sofisticiranost i individualnost. Vjerujemo da nakit ima moć da promijeni način na koji se osjećate, dodajući dašak luksuza i elegancije vašem izgledu',
        kategorija: "Nausnice",
        price: 21.95,
        imageSrc: '/ogrlica1.jpeg',
        imageAlt: 'Neki opis proizvoda',
    },
]